package com.hardwarehub.user_service.enums;

public enum Permission
{
    // CREATE, READ, UPDATE, DELETE

    ROLE_UPDATE,

    ADMIN_READ,

    STAFF_READ, STAFF_DELETE,

    CUSTOMER_READ, CUSTOMER_DELETE,

    PRODUCT_CREATE, PRODUCT_READ, PRODUCT_UPDATE, PRODUCT_DELETE,

    ORDER_READ, ORDER_UPDATE,

    ORDER_ITEM_CREATE, ORDER_ITEM_UPDATE, ORDER_ITEM_DELETE
}
